#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun  4 14:12:03 2021

@author: wangchenxi
"""

# =============================================================================
# import tensorflow.compat.v1 as tf
# 
# state=tf.Variable(0,name='counter')#在tf中只有用Variable定义才可以定义变量，初始值为0，名字是counter
# print(state.name)
# one=tf.constant(1)#定义常亮用constant
# 
# new_value=tf.add(state,one)
# update=tf.assign(state,new_value)#将new_value值赋给state
# 
# init=tf.initialize_all_variables()#初始化，如果定义了变量一定要有这一步
# 
# 
# with tf.Session() as sess:
#     sess.run(init)
#     for i in range(3):
#         sess.run(update)
#         print(sess.run(state))#注意此处一定要加sess.run()才能打印出变量
# =============================================================================
import tensorflow as tf
a=tf.constant([1,5],dtype=tf.int64)
print(a)
print(a.eval)